//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/GameMainAllSystem/GameInputSystem/GameInputingSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/GameMainAllSystem/GameInputSystem/GameInputingSystem.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputingSystem: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputingSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameInputingSystem"",
    ""maps"": [
        {
            ""name"": ""TankerDriver"",
            ""id"": ""f831cbf8-8f6f-4228-aa43-865885a9ba5b"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""705be9f3-dee4-4ae3-a54f-09e6e5aa502a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""7b171c35-2170-48db-925e-93ab22d77b6c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftTurn"",
                    ""type"": ""Button"",
                    ""id"": ""432af146-47a0-430b-86e9-fb71234cdd53"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTurn"",
                    ""type"": ""Button"",
                    ""id"": ""e9d38444-8e28-46da-908e-3b83815908cf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""cea2ee66-124b-449b-a2ee-5f85e87ae5ea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""910475d3-8299-46fa-9875-c86307621b5d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomFOV"",
                    ""type"": ""Button"",
                    ""id"": ""0922f3b6-b1fe-48cf-aed4-760e512b85db"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeLooking"",
                    ""type"": ""Button"",
                    ""id"": ""3e8ca658-b077-421d-887c-0f2c74cfb9c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7184baed-cb0b-4ceb-a979-3cf4f0019a01"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GunAim"",
                    ""type"": ""Button"",
                    ""id"": ""93a2d36d-c108-4f0e-ab19-4066570d9d97"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MachinegunFire"",
                    ""type"": ""Button"",
                    ""id"": ""0e10165d-d1b0-4581-890f-ae47a7e6dabe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EngineSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""f266e7e0-931f-4479-8a7a-e1460c9d6b6f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thermalmaging"",
                    ""type"": ""Button"",
                    ""id"": ""3e4a64f5-4575-4d8f-84b3-46debe96c541"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rangefinder"",
                    ""type"": ""Button"",
                    ""id"": ""4e8e506c-5515-4d20-9769-06c13b8b8db2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MIssionLabShow"",
                    ""type"": ""Button"",
                    ""id"": ""93c20693-df85-4b7f-87e9-088f039dfe31"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MapShow"",
                    ""type"": ""Button"",
                    ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad549a8c-01ad-4d3c-b6b1-c14dd7bc171c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59a55069-40e1-4e5d-af31-7a3b75ab7003"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f099261-3f28-4b81-8aef-4b468aaec815"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58be0d6c-71f1-4f69-a059-5c2b15a0d5b5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ec94c50-9509-464d-9958-a0d98e73e486"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a1deb5f-bdb3-488a-affe-311793b8f0ec"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3ce57f9-6002-49d4-b82a-abfbc5ca8ecb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1e90e9d-4c57-4011-8d53-59099b89b4b9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomFOV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3096a63b-bbd4-4979-ae0a-bc47dcf3caca"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeLooking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8efe81-3fd2-44d7-8632-99162c8939c7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GunAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8fb7a48-fb53-4f94-9ab4-7bcc4a0c1e32"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MachinegunFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53d260df-c43d-4290-885f-24203f1a9c95"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EngineSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9eda36c-1d3d-40a5-8e7d-ed3a201f5559"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thermalmaging"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2c44c02-a091-4f75-8190-f61423f91b2a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rangefinder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40a4de5b-1c3d-4e6b-ac0b-0df104a921db"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MIssionLabShow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2c3d4e5-f6a7-8901-bcde-f12345678901"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapShow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TankerDriver
        m_TankerDriver = asset.FindActionMap("TankerDriver", throwIfNotFound: true);
        m_TankerDriver_Forward = m_TankerDriver.FindAction("Forward", throwIfNotFound: true);
        m_TankerDriver_Back = m_TankerDriver.FindAction("Back", throwIfNotFound: true);
        m_TankerDriver_LeftTurn = m_TankerDriver.FindAction("LeftTurn", throwIfNotFound: true);
        m_TankerDriver_RightTurn = m_TankerDriver.FindAction("RightTurn", throwIfNotFound: true);
        m_TankerDriver_Fire = m_TankerDriver.FindAction("Fire", throwIfNotFound: true);
        m_TankerDriver_Reload = m_TankerDriver.FindAction("Reload", throwIfNotFound: true);
        m_TankerDriver_ZoomFOV = m_TankerDriver.FindAction("ZoomFOV", throwIfNotFound: true);
        m_TankerDriver_FreeLooking = m_TankerDriver.FindAction("FreeLooking", throwIfNotFound: true);
        m_TankerDriver_Pause = m_TankerDriver.FindAction("Pause", throwIfNotFound: true);
        m_TankerDriver_GunAim = m_TankerDriver.FindAction("GunAim", throwIfNotFound: true);
        m_TankerDriver_MachinegunFire = m_TankerDriver.FindAction("MachinegunFire", throwIfNotFound: true);
        m_TankerDriver_EngineSwitch = m_TankerDriver.FindAction("EngineSwitch", throwIfNotFound: true);
        m_TankerDriver_Thermalmaging = m_TankerDriver.FindAction("Thermalmaging", throwIfNotFound: true);
        m_TankerDriver_Rangefinder = m_TankerDriver.FindAction("Rangefinder", throwIfNotFound: true);
        m_TankerDriver_MIssionLabShow = m_TankerDriver.FindAction("MIssionLabShow", throwIfNotFound: true);
        m_TankerDriver_MapShow = m_TankerDriver.FindAction("MapShow", throwIfNotFound: true);
    }

    ~@GameInputingSystem()
    {
        UnityEngine.Debug.Assert(!m_TankerDriver.enabled, "This will cause a leak and performance issues, GameInputingSystem.TankerDriver.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TankerDriver
    private readonly InputActionMap m_TankerDriver;
    private List<ITankerDriverActions> m_TankerDriverActionsCallbackInterfaces = new List<ITankerDriverActions>();
    private readonly InputAction m_TankerDriver_Forward;
    private readonly InputAction m_TankerDriver_Back;
    private readonly InputAction m_TankerDriver_LeftTurn;
    private readonly InputAction m_TankerDriver_RightTurn;
    private readonly InputAction m_TankerDriver_Fire;
    private readonly InputAction m_TankerDriver_Reload;
    private readonly InputAction m_TankerDriver_ZoomFOV;
    private readonly InputAction m_TankerDriver_FreeLooking;
    private readonly InputAction m_TankerDriver_Pause;
    private readonly InputAction m_TankerDriver_GunAim;
    private readonly InputAction m_TankerDriver_MachinegunFire;
    private readonly InputAction m_TankerDriver_EngineSwitch;
    private readonly InputAction m_TankerDriver_Thermalmaging;
    private readonly InputAction m_TankerDriver_Rangefinder;
    private readonly InputAction m_TankerDriver_MIssionLabShow;
    private readonly InputAction m_TankerDriver_MapShow;
    /// <summary>
    /// Provides access to input actions defined in input action map "TankerDriver".
    /// </summary>
    public struct TankerDriverActions
    {
        private @GameInputingSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TankerDriverActions(@GameInputingSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Forward".
        /// </summary>
        public InputAction @Forward => m_Wrapper.m_TankerDriver_Forward;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Back".
        /// </summary>
        public InputAction @Back => m_Wrapper.m_TankerDriver_Back;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/LeftTurn".
        /// </summary>
        public InputAction @LeftTurn => m_Wrapper.m_TankerDriver_LeftTurn;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/RightTurn".
        /// </summary>
        public InputAction @RightTurn => m_Wrapper.m_TankerDriver_RightTurn;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Fire".
        /// </summary>
        public InputAction @Fire => m_Wrapper.m_TankerDriver_Fire;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Reload".
        /// </summary>
        public InputAction @Reload => m_Wrapper.m_TankerDriver_Reload;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/ZoomFOV".
        /// </summary>
        public InputAction @ZoomFOV => m_Wrapper.m_TankerDriver_ZoomFOV;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/FreeLooking".
        /// </summary>
        public InputAction @FreeLooking => m_Wrapper.m_TankerDriver_FreeLooking;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_TankerDriver_Pause;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/GunAim".
        /// </summary>
        public InputAction @GunAim => m_Wrapper.m_TankerDriver_GunAim;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/MachinegunFire".
        /// </summary>
        public InputAction @MachinegunFire => m_Wrapper.m_TankerDriver_MachinegunFire;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/EngineSwitch".
        /// </summary>
        public InputAction @EngineSwitch => m_Wrapper.m_TankerDriver_EngineSwitch;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Thermalmaging".
        /// </summary>
        public InputAction @Thermalmaging => m_Wrapper.m_TankerDriver_Thermalmaging;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/Rangefinder".
        /// </summary>
        public InputAction @Rangefinder => m_Wrapper.m_TankerDriver_Rangefinder;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/MIssionLabShow".
        /// </summary>
        public InputAction @MIssionLabShow => m_Wrapper.m_TankerDriver_MIssionLabShow;
        /// <summary>
        /// Provides access to the underlying input action "TankerDriver/MapShow".
        /// </summary>
        public InputAction @MapShow => m_Wrapper.m_TankerDriver_MapShow;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TankerDriver; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TankerDriverActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TankerDriverActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TankerDriverActions" />
        public void AddCallbacks(ITankerDriverActions instance)
        {
            if (instance == null || m_Wrapper.m_TankerDriverActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TankerDriverActionsCallbackInterfaces.Add(instance);
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @LeftTurn.started += instance.OnLeftTurn;
            @LeftTurn.performed += instance.OnLeftTurn;
            @LeftTurn.canceled += instance.OnLeftTurn;
            @RightTurn.started += instance.OnRightTurn;
            @RightTurn.performed += instance.OnRightTurn;
            @RightTurn.canceled += instance.OnRightTurn;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @ZoomFOV.started += instance.OnZoomFOV;
            @ZoomFOV.performed += instance.OnZoomFOV;
            @ZoomFOV.canceled += instance.OnZoomFOV;
            @FreeLooking.started += instance.OnFreeLooking;
            @FreeLooking.performed += instance.OnFreeLooking;
            @FreeLooking.canceled += instance.OnFreeLooking;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @GunAim.started += instance.OnGunAim;
            @GunAim.performed += instance.OnGunAim;
            @GunAim.canceled += instance.OnGunAim;
            @MachinegunFire.started += instance.OnMachinegunFire;
            @MachinegunFire.performed += instance.OnMachinegunFire;
            @MachinegunFire.canceled += instance.OnMachinegunFire;
            @EngineSwitch.started += instance.OnEngineSwitch;
            @EngineSwitch.performed += instance.OnEngineSwitch;
            @EngineSwitch.canceled += instance.OnEngineSwitch;
            @Thermalmaging.started += instance.OnThermalmaging;
            @Thermalmaging.performed += instance.OnThermalmaging;
            @Thermalmaging.canceled += instance.OnThermalmaging;
            @Rangefinder.started += instance.OnRangefinder;
            @Rangefinder.performed += instance.OnRangefinder;
            @Rangefinder.canceled += instance.OnRangefinder;
            @MIssionLabShow.started += instance.OnMIssionLabShow;
            @MIssionLabShow.performed += instance.OnMIssionLabShow;
            @MIssionLabShow.canceled += instance.OnMIssionLabShow;
            @MapShow.started += instance.OnMapShow;
            @MapShow.performed += instance.OnMapShow;
            @MapShow.canceled += instance.OnMapShow;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TankerDriverActions" />
        private void UnregisterCallbacks(ITankerDriverActions instance)
        {
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @LeftTurn.started -= instance.OnLeftTurn;
            @LeftTurn.performed -= instance.OnLeftTurn;
            @LeftTurn.canceled -= instance.OnLeftTurn;
            @RightTurn.started -= instance.OnRightTurn;
            @RightTurn.performed -= instance.OnRightTurn;
            @RightTurn.canceled -= instance.OnRightTurn;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @ZoomFOV.started -= instance.OnZoomFOV;
            @ZoomFOV.performed -= instance.OnZoomFOV;
            @ZoomFOV.canceled -= instance.OnZoomFOV;
            @FreeLooking.started -= instance.OnFreeLooking;
            @FreeLooking.performed -= instance.OnFreeLooking;
            @FreeLooking.canceled -= instance.OnFreeLooking;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @GunAim.started -= instance.OnGunAim;
            @GunAim.performed -= instance.OnGunAim;
            @GunAim.canceled -= instance.OnGunAim;
            @MachinegunFire.started -= instance.OnMachinegunFire;
            @MachinegunFire.performed -= instance.OnMachinegunFire;
            @MachinegunFire.canceled -= instance.OnMachinegunFire;
            @EngineSwitch.started -= instance.OnEngineSwitch;
            @EngineSwitch.performed -= instance.OnEngineSwitch;
            @EngineSwitch.canceled -= instance.OnEngineSwitch;
            @Thermalmaging.started -= instance.OnThermalmaging;
            @Thermalmaging.performed -= instance.OnThermalmaging;
            @Thermalmaging.canceled -= instance.OnThermalmaging;
            @Rangefinder.started -= instance.OnRangefinder;
            @Rangefinder.performed -= instance.OnRangefinder;
            @Rangefinder.canceled -= instance.OnRangefinder;
            @MIssionLabShow.started -= instance.OnMIssionLabShow;
            @MIssionLabShow.performed -= instance.OnMIssionLabShow;
            @MIssionLabShow.canceled -= instance.OnMIssionLabShow;
            @MapShow.started -= instance.OnMapShow;
            @MapShow.performed -= instance.OnMapShow;
            @MapShow.canceled -= instance.OnMapShow;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TankerDriverActions.UnregisterCallbacks(ITankerDriverActions)" />.
        /// </summary>
        /// <seealso cref="TankerDriverActions.UnregisterCallbacks(ITankerDriverActions)" />
        public void RemoveCallbacks(ITankerDriverActions instance)
        {
            if (m_Wrapper.m_TankerDriverActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TankerDriverActions.AddCallbacks(ITankerDriverActions)" />
        /// <seealso cref="TankerDriverActions.RemoveCallbacks(ITankerDriverActions)" />
        /// <seealso cref="TankerDriverActions.UnregisterCallbacks(ITankerDriverActions)" />
        public void SetCallbacks(ITankerDriverActions instance)
        {
            foreach (var item in m_Wrapper.m_TankerDriverActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TankerDriverActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TankerDriverActions" /> instance referencing this action map.
    /// </summary>
    public TankerDriverActions @TankerDriver => new TankerDriverActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TankerDriver" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TankerDriverActions.AddCallbacks(ITankerDriverActions)" />
    /// <seealso cref="TankerDriverActions.RemoveCallbacks(ITankerDriverActions)" />
    public interface ITankerDriverActions
    {
        /// <summary>
        /// Method invoked when associated input action "Forward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnForward(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Back" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftTurn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftTurn(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightTurn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightTurn(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Fire" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFire(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reload" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReload(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ZoomFOV" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoomFOV(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FreeLooking" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFreeLooking(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GunAim" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGunAim(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MachinegunFire" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMachinegunFire(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EngineSwitch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEngineSwitch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Thermalmaging" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThermalmaging(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rangefinder" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRangefinder(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MIssionLabShow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMIssionLabShow(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MapShow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMapShow(InputAction.CallbackContext context);
    }
}
